### ISSUE TITLE
Some of the Images selected, the images URI is undefined

### ISSUE THREAD

**Issue by clarklight** [abelabbesnabi/cordova-plugin-image-picker#1]
Hey man 

 Thanks for adding in the permission part, but i just experienced that some images selected it doesn't return a URI, it is shown as undefined at the moment. 

Not sure why at the moment, i have tested on Android 5.0, android 7.0 on LG, Samsung, on Phonegap 6.4.0.

**Comment by abelabbesnabi** [comment]
I'm not sure why. I only forked the main plugin to fix the permission problem. The rest of the code is identical.
Can you attach those images that are causing the issue? I will add them to my phone gallery and see if I can  replicate.
Thanks.

**Comment by clarklight** [comment]
Hi, i guess its not the specific images, i just took a picture on my camera, and tried to select that, it doesnt show up either.  I am just taking a look again to see the URI results etc 

But 1 thing i see is, for the images that doesn't show up, the app will flash then back to normal. But the URI would be undefined. 

It seems like any picture from the Camera folder won't get uploaded. But when i tried like pictures i got from whatsapp, then that had no problem. 

Thanks i will keep digging and update you if i find any more info.

**Comment by abelabbesnabi** [comment]
Ok. Seems like this problem might not be with the plugin itself. If so, maybe we should consider closing this issue. Let me know how it goes.

**Comment by clarklight** [comment]
I just gave it a go again the results[i] is undefined. I simply took a picture with the camera and  just select that image through the plugin.  Not sure if this would be the problem but i included your version within my config.xml like this 

<plugin spec="https://github.com/abelabbesnabi/cordova-plugin-image-picker" source="git" />

Do you have a npm version? 

Thanks

**Comment by abelabbesnabi** [comment]
No, I don't :(

**Comment by clarklight** [comment]
Spent hours.. found the reason finally, nothing to do with the plugin. Closing the issue, Thanks for the help/response.

**Comment by abelabbesnabi** [comment]
Excellent!
